[package]
name = "rust-threads-study"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
rand = "0.8.5"
rayon = "1.10.0"
rayon-core = "1.12.1"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
surrealdb = "1.5.4"
tokio = "1.40.0"
uuid = "1.10.0"
